import type { NextPage } from 'next';
// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
import { Header } from '../components/local/header';
import { Div, Head } from '../components/shared/atomicUI/atoms';
import { SocialLinks } from '../components/shared/atomicUI/molecules';

const Home: NextPage = () => {
  return (
    <Div colorize highlight>
      <Head
        title="JP Portfolio Home"
        description="Generated by create next app"
        icon="/favicon.ico"
      />
      <Header />
      <main>
      <SocialLinks />
      </main>
    </Div>
  );
};

export default Home;
